name: Docker Build and Push

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      USER_MICROSERVICES: ${{ secrets.USER_MICROSERVICES }}
      AUTH_MICROSERVICES: ${{ secrets.AUTH_MICROSERVICES }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: docker build -t api-gateway:1.0.0 .

    - name: Tag Docker image
      run: docker tag api-gateway:1.0.0 "${{ secrets.DOCKER_USERNAME }}/api-gateway:1.0.0"

    - name: Push Docker image
      run: docker push "${{ secrets.DOCKER_USERNAME }}/api-gateway:1.0.0"

    - name: Clean up temporary files
      run: |
        # Remove temporary Docker image
        docker rmi api-gateway:1.0.0

        # Remove Docker image tag
        docker rmi "${{ secrets.DOCKER_USERNAME }}/api-gateway:1.0.0"